"""making embedding column have 768 vec

Revision ID: 384316cd5dc8
Revises: 6699d6ebbf85
Create Date: 2024-07-21 16:11:15.703424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '384316cd5dc8'
down_revision: Union[str, None] = '6699d6ebbf85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
                    existing_nullable=True)
    # ### end Alembic commands ###
