"""changing username to phone_number in users table

Revision ID: 1bc39708f0cd
Revises: 58a6038e865a
Create Date: 2024-07-11 08:31:50.176590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc39708f0cd'
down_revision: Union[str, None] = '58a6038e865a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number',
                  sa.String(length=10), nullable=True))
    op.execute(
        'UPDATE users SET phone_number = \'6788973910\' WHERE phone_number IS NULL')
    op.alter_column('users', 'phone_number', nullable=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
